global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apis'
    static_configs:
      - targets: ['ms_apiproducts:80', 'ms_apibilling:80', 'ms_sendnotifications:80', 'ms_sendtaxes:80', 'ms_sendtaxesworker:80']
  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']